"""Russian phonetic -> English tech term replacements.
Curated (D024): single-word Cyrillic keys that are real Russian words
were removed so the dictionary only fires on unambiguous English
phonetics, product/library names and code identifiers. See
tools/clean_terms.py for the reproducible rule.
"""

TERM_REPLACEMENTS = {
    "юзстейт": "useState",
    "юз стейт": "useState",
    "юстейт": "useState",
    "юстэйт": "useState",
    "юстет": "useState",
    "ю стейт": "useState",
    "ю стэйт": "useState",
    "ю стейд": "useState",
    "юстейд": "useState",
    "ю стэйд": "useState",
    "юзэффект": "useEffect",
    "юз эффект": "useEffect",
    "юзконтекст": "useContext",
    "юз контекст": "useContext",
    "юзреф": "useRef",
    "юз реф": "useRef",
    "юзмемо": "useMemo",
    "юз мемо": "useMemo",
    "юзколбэк": "useCallback",
    "юз колбэк": "useCallback",
    "юзредьюсер": "useReducer",
    "юз редьюсер": "useReducer",
    "юзлэйаут эффект": "useLayoutEffect",
    "юзимперативхендл": "useImperativeHandle",
    "пропс": "props",
    "пропсы": "props",
    "стейт": "state",
    "сетстейт": "setState",
    "хуки": "hooks",
    "консьюмер": "consumer",
    "редьюсер": "reducer",
    "экшен": "action",
    "диспатч": "dispatch",
    "редакс": "Redux",
    "мобэкс": "MobX",
    "зустанд": "Zustand",
    "джотай": "Jotai",
    "рекойл": "Recoil",
    "джаваскрипт": "JavaScript",
    "джава скрипт": "JavaScript",
    "яваскрипт": "JavaScript",
    "ява скрипт": "JavaScript",
    "ява-скрипт": "JavaScript",
    "джс": "JS",
    "тайпскрипт": "TypeScript",
    "тайп скрипт": "TypeScript",
    "тайпск": "TypeScript",
    "пайтон": "Python",
    "джава": "Java",
    "котлин": "Kotlin",
    "свифт": "Swift",
    "обджектив си": "Objective-C",
    "сишарп": "C#",
    "си шарп": "C#",
    "сиплюсплюс": "C++",
    "си плюс плюс": "C++",
    "гоу": "Go",
    "голанг": "Golang",
    "раст": "Rust",
    "пхп": "PHP",
    "пиэйчпи": "PHP",
    "кложур": "Clojure",
    "хаскелл": "Haskell",
    "эрланг": "Erlang",
    "люа": "Lua",
    "дарт": "Dart",
    "зиг": "Zig",
    "реакт": "React",
    "риэкт": "React",
    "вью": "Vue",
    "вьюджс": "Vue.js",
    "ангуляр": "Angular",
    "свелт": "Svelte",
    "свелткит": "SvelteKit",
    "некст": "Next.js",
    "некстджс": "Next.js",
    "нукст": "Nuxt",
    "нукстджс": "Nuxt.js",
    "гэтсби": "Gatsby",
    "астро": "Astro",
    "солид": "Solid",
    "солиджс": "SolidJS",
    "квик": "Qwik",
    "преакт": "Preact",
    "алпайн": "Alpine.js",
    "эмбер": "Ember",
    "бэкбон": "Backbone",
    "джейквери": "jQuery",
    "джи квери": "jQuery",
    "ноджс": "Node.js",
    "нод": "Node",
    "экспрессджс": "Express.js",
    "фастифай": "Fastify",
    "коа": "Koa",
    "нест": "Nest",
    "нестджс": "NestJS",
    "джанго": "Django",
    "фласк": "Flask",
    "фастапи": "FastAPI",
    "фаст апи": "FastAPI",
    "эйоник": "aiohttp",
    "рейлс": "Rails",
    "руби он рейлс": "Ruby on Rails",
    "ларавел": "Laravel",
    "симфони": "Symfony",
    "спринг": "Spring",
    "спринг бут": "Spring Boot",
    "файбер": "Fiber",
    "актикс": "Actix",
    "рокет": "Rocket",
    "флаттер": "Flutter",
    "реакт нейтив": "React Native",
    "таури": "Tauri",
    "цсс": "CSS",
    "сиэсэс": "CSS",
    "сасс": "Sass",
    "скссс": "SCSS",
    "лесс": "Less",
    "стайлус": "Stylus",
    "тейлвинд": "Tailwind",
    "тэйлвинд": "Tailwind",
    "бутстрап": "Bootstrap",
    "материал юай": "Material UI",
    "чакра": "Chakra",
    "чакра юай": "Chakra UI",
    "энт дизайн": "Ant Design",
    "стайлд компонентс": "styled-components",
    "эмоушн": "Emotion",
    "флексбокс": "Flexbox",
    "флекс": "flex",
    "грид": "grid",
    "медиа квери": "media query",
    "вебпак": "Webpack",
    "вайт": "Vite",
    "роллап": "Rollup",
    "парсел": "Parcel",
    "есбилд": "esbuild",
    "свц": "SWC",
    "бабель": "Babel",
    "бейбл": "Babel",
    "тёрбо": "Turbo",
    "турбопак": "Turbopack",
    "турборепо": "Turborepo",
    "лёрна": "Lerna",
    "нх": "Nx",
    "нпм": "npm",
    "энпиэм": "npm",
    "ярн": "yarn",
    "пнпм": "pnpm",
    "пип": "pip",
    "пипенв": "pipenv",
    "поэтри": "poetry",
    "композер": "composer",
    "мавен": "Maven",
    "грэдл": "Gradle",
    "кокоаподс": "CocoaPods",
    "брю": "brew",
    "хоумбрю": "Homebrew",
    "чоко": "choco",
    "чоколати": "Chocolatey",
    "джест": "Jest",
    "витест": "Vitest",
    "мока": "Mocha",
    "сайпресс": "Cypress",
    "плейврайт": "Playwright",
    "паппетир": "Puppeteer",
    "селениум": "Selenium",
    "юнит тест": "unit test",
    "юнит тесты": "unit tests",
    "интеграционный тест": "integration test",
    "е ту е": "e2e",
    "иту|и": "e2e",
    "энд ту энд": "end-to-end",
    "моки": "mocks",
    "стаб": "stub",
    "спай": "spy",
    "фикстура": "fixture",
    "ассерт": "assert",
    "эксепт": "expect",
    "тест кейс": "test case",
    "тест сьют": "test suite",
    "ковередж": "coverage",
    "гит": "git",
    "гитхаб": "GitHub",
    "гитлаб": "GitLab",
    "битбакет": "Bitbucket",
    "коммит": "commit",
    "коммиты": "commits",
    "пуш": "push",
    "пушить": "push",
    "пулить": "pull",
    "фетч": "fetch",
    "пулл реквест": "pull request",
    "пул реквест": "pull request",
    "пи ар": "PR",
    "мёрдж": "merge",
    "мердж": "merge",
    "мёрджить": "merge",
    "бранч": "branch",
    "бранчи": "branches",
    "ребейз": "rebase",
    "черри пик": "cherry-pick",
    "черрипик": "cherry-pick",
    "сташ": "stash",
    "стэш": "stash",
    "чекаут": "checkout",
    "чек аут": "checkout",
    "ресет": "reset",
    "риверт": "revert",
    "дифф": "diff",
    "блейм": "blame",
    "ориджин": "origin",
    "апстрим": "upstream",
    "ремоут": "remote",
    "хед": "HEAD",
    "мейн": "main",
    "девелоп": "develop",
    "фича": "feature",
    "хотфикс": "hotfix",
    "гитигнор": ".gitignore",
    "докер": "Docker",
    "докерфайл": "Dockerfile",
    "докер компоуз": "docker-compose",
    "имейдж": "image",
    "кубернетес": "Kubernetes",
    "кубер": "Kubernetes",
    "кейт эйт эс": "K8s",
    "кубернетис": "Kubernetes",
    "хелм": "Helm",
    "истио": "Istio",
    "терраформ": "Terraform",
    "ансибл": "Ansible",
    "паппет": "Puppet",
    "вагрант": "Vagrant",
    "дженкинс": "Jenkins",
    "гитхаб экшенс": "GitHub Actions",
    "гитлаб сиай": "GitLab CI",
    "сиай сиди": "CI/CD",
    "си ай": "CI",
    "си ди": "CD",
    "пайплайн": "pipeline",
    "деплой": "deploy",
    "деплоймент": "deployment",
    "продакшен": "production",
    "прод": "prod",
    "стейджинг": "staging",
    "стейдж": "stage",
    "дев": "dev",
    "локал": "local",
    "энвайронмент": "environment",
    "энв": "env",
    "конфиг": "config",
    "авс": "AWS",
    "эйдаблюэс": "AWS",
    "амазон": "Amazon",
    "эй даблю эс": "AWS",
    "гугл клауд": "Google Cloud",
    "джисипи": "GCP",
    "азур": "Azure",
    "эйжур": "Azure",
    "майкрософт азур": "Microsoft Azure",
    "дигитал оушен": "DigitalOcean",
    "херроку": "Heroku",
    "хероку": "Heroku",
    "верцель": "Vercel",
    "версель": "Vercel",
    "нетлифай": "Netlify",
    "клаудфлер": "Cloudflare",
    "файрбейз": "Firebase",
    "фаербейс": "Firebase",
    "сюпабейз": "Supabase",
    "супабейс": "Supabase",
    "планетскейл": "PlanetScale",
    "рейлвей": "Railway",
    "флай ио": "Fly.io",
    "постгрес": "PostgreSQL",
    "постгрескюэл": "PostgreSQL",
    "постгря": "Postgres",
    "майскюэл": "MySQL",
    "маскюэл": "MySQL",
    "скюлайт": "SQLite",
    "скюэлайт": "SQLite",
    "монго": "MongoDB",
    "монгодиби": "MongoDB",
    "редис": "Redis",
    "мемкэшд": "Memcached",
    "эластиксёрч": "Elasticsearch",
    "эластик": "Elastic",
    "кассандра": "Cassandra",
    "динамодиби": "DynamoDB",
    "коучдиби": "CouchDB",
    "нео фор джей": "Neo4j",
    "скюэл": "SQL",
    "эскуэль": "SQL",
    "ноускюэл": "NoSQL",
    "орм": "ORM",
    "призма": "Prisma",
    "секвелайз": "Sequelize",
    "тайпорм": "TypeORM",
    "дризл": "Drizzle",
    "алембик": "Alembic",
    "сидинг": "seeding",
    "сид": "seed",
    "скима": "schema",
    "квери": "query",
    "кверя": "query",
    "джойн": "join",
    "лефт джойн": "LEFT JOIN",
    "иннер джойн": "INNER JOIN",
    "веар": "WHERE",
    "ордер бай": "ORDER BY",
    "груп бай": "GROUP BY",
    "хэвинг": "HAVING",
    "оффсет": "OFFSET",
    "эй пи ай": "API",
    "апи": "API",
    "рест": "REST",
    "рестфул": "RESTful",
    "графкюэл": "GraphQL",
    "граф кюэл": "GraphQL",
    "джейсон": "JSON",
    "джсон": "JSON",
    "иксэмэл": "XML",
    "хмл": "XML",
    "эйчтиэмэл": "HTML",
    "хтмл": "HTML",
    "ямл": "YAML",
    "йамл": "YAML",
    "томл": "TOML",
    "эйчтитипи": "HTTP",
    "хттп": "HTTP",
    "эйчтитипиэс": "HTTPS",
    "хттпс": "HTTPS",
    "вебсокет": "WebSocket",
    "веб сокет": "WebSocket",
    "сокет": "socket",
    "сокеты": "sockets",
    "сокет ио": "Socket.io",
    "грпц": "gRPC",
    "джиарписи": "gRPC",
    "тиарписи": "tRPC",
    "оаус": "OAuth",
    "о аус": "OAuth",
    "джейдаблютэ": "JWT",
    "джот": "JWT",
    "эндпоинт": "endpoint",
    "эндпоинты": "endpoints",
    "роут": "route",
    "роуты": "routes",
    "роутер": "router",
    "роутинг": "routing",
    "мидлвер": "middleware",
    "мидлвэр": "middleware",
    "хедер": "header",
    "хедеры": "headers",
    "хэдер": "header",
    "бади": "body",
    "боди": "body",
    "пэйлоад": "payload",
    "пейлоад": "payload",
    "респонс": "response",
    "респонсы": "responses",
    "реквест": "request",
    "реквесты": "requests",
    "статус код": "status code",
    "корс": "CORS",
    "вебхук": "webhook",
    "вебхуки": "webhooks",
    "девин": "Devin",
    "клод": "Claude",
    "джипити": "GPT",
    "чатджипити": "ChatGPT",
    "чат джипити": "ChatGPT",
    "опенэйай": "OpenAI",
    "опен эй ай": "OpenAI",
    "антропик": "Anthropic",
    "копайлот": "Copilot",
    "коупайлот": "Copilot",
    "джемини": "Gemini",
    "промт": "prompt",
    "промпт": "prompt",
    "промты": "prompts",
    "промпты": "prompts",
    "эмбеддинг": "embedding",
    "эмбеддинги": "embeddings",
    "файнтюнинг": "fine-tuning",
    "файн тюнинг": "fine-tuning",
    "инференс": "inference",
    "трансформер": "transformer",
    "аттеншен": "attention",
    "лангчейн": "LangChain",
    "ланг чейн": "LangChain",
    "лламаиндекс": "LlamaIndex",
    "пайторч": "PyTorch",
    "тензорфлоу": "TensorFlow",
    "керас": "Keras",
    "сайкитлёрн": "scikit-learn",
    "хаггингфейс": "Hugging Face",
    "функшн": "function",
    "фанкшн": "function",
    "дифолт": "default",
    "конст": "const",
    "вар": "var",
    "иф": "if",
    "элс": "else",
    "элс иф": "else if",
    "фор": "for",
    "форич": "forEach",
    "фор ич": "forEach",
    "вайл": "while",
    "ду вайл": "do while",
    "свитч": "switch",
    "континью": "continue",
    "ретурн": "return",
    "риторн": "return",
    "ретёрн": "return",
    "трай": "try",
    "кэтч": "catch",
    "файналли": "finally",
    "троу": "throw",
    "сроу": "throw",
    "зис": "this",
    "экстендс": "extends",
    "имплементс": "implements",
    "статик": "static",
    "паблик": "public",
    "прайват": "private",
    "протектед": "protected",
    "эсинк": "async",
    "эсюнк": "async",
    "эвейт": "await",
    "авэйт": "await",
    "йилд": "yield",
    "йелд": "yield",
    "промис": "Promise",
    "промисы": "promises",
    "эррор": "error",
    "эксепшн": "exception",
    "эксепшен": "exception",
    "тайп": "type",
    "тайпы": "types",
    "стринг": "string",
    "стринги": "strings",
    "намбер": "number",
    "намберы": "numbers",
    "буллеан": "boolean",
    "булеан": "boolean",
    "бул": "bool",
    "булл": "boolean",
    "эррей": "array",
    "эррэй": "array",
    "обджект": "object",
    "нулл": "null",
    "налл": "null",
    "андефайнд": "undefined",
    "войд": "void",
    "эни": "any",
    "анноун": "unknown",
    "невер": "never",
    "тупл": "tuple",
    "тюпл": "tuple",
    "энам": "enum",
    "инам": "enum",
    "юнион": "union",
    "дженерик": "generic",
    "дженерики": "generics",
    "тайпоф": "typeof",
    "тайп оф": "typeof",
    "кейоф": "keyof",
    "кей оф": "keyof",
    "ридонли": "readonly",
    "рид онли": "readonly",
    "партиал": "Partial",
    "омит": "Omit",
    "эксклуд": "Exclude",
    "нон наллабл": "NonNullable",
    "ретурн тайп": "ReturnType",
    "вариабл": "variable",
    "колбэк": "callback",
    "колбек": "callback",
    "хендлер": "handler",
    "хэндлер": "handler",
    "листенер": "listener",
    "ивент": "event",
    "евент": "event",
    "ивенты": "events",
    "эмит": "emit",
    "эмитить": "emit",
    "сабскрайб": "subscribe",
    "ансабскрайб": "unsubscribe",
    "обсёрвер": "observer",
    "обсервер": "observer",
    "итерировать": "iterate",
    "луп": "loop",
    "кондишн": "condition",
    "тернарный": "ternary",
    "инкремент": "increment",
    "декремент": "decrement",
    "деструктуризация": "destructuring",
    "спред": "spread",
    "дефолт вэлью": "default value",
    "стек": "stack",
    "кью": "queue",
    "дек": "deque",
    "линкд лист": "linked list",
    "связный список": "linked list",
    "бинарное дерево": "binary tree",
    "бинари три": "binary tree",
    "хэшмэп": "hashmap",
    "хешмап": "hashmap",
    "мап": "map",
    "мапа": "map",
    "мэп": "map",
    "дикт": "dict",
    "нода": "node",
    "ноды": "nodes",
    "эдж": "edge",
    "вертекс": "vertex",
    "рут": "root",
    "парент": "parent",
    "чайлд": "child",
    "чилдрен": "children",
    "сиблинг": "sibling",
    "ооп": "OOP",
    "о о п": "OOP",
    "объектно ориентированный": "object-oriented",
    "инхеританс": "inheritance",
    "деструктор": "destructor",
    "инстанс": "instance",
    "инстансы": "instances",
    "проперти": "property",
    "пропертис": "properties",
    "геттер": "getter",
    "сеттер": "setter",
    "аксессор": "accessor",
    "мутатор": "mutator",
    "оверрайд": "override",
    "оверлоад": "overload",
    "эфпи": "FP",
    "чистая функция": "pure function",
    "пьюр фанкшн": "pure function",
    "иммутабл": "immutable",
    "иммьютабл": "immutable",
    "мутабл": "mutable",
    "мьютабл": "mutable",
    "сайд эффект": "side effect",
    "хайер ордер": "higher order",
    "хоф": "HOF",
    "карринг": "currying",
    "пайп": "pipe",
    "фильтер": "filter",
    "редьюс": "reduce",
    "фолд": "fold",
    "флэтмэп": "flatMap",
    "флэт": "flat",
    "фаинд": "find",
    "файнд": "find",
    "эври": "every",
    "инклудс": "includes",
    "индексоф": "indexOf",
    "слайс": "slice",
    "сплайс": "splice",
    "конкат": "concat",
    "трим": "trim",
    "сабстринг": "substring",
    "репсейс": "replace",
    "реплейс": "replace",
    "серч": "search",
    "ди оу эм": "DOM",
    "виндоу": "window",
    "квери селектор": "querySelector",
    "гет элемент бай айди": "getElementById",
    "гет элементс бай класс": "getElementsByClassName",
    "криейт элемент": "createElement",
    "аппенд": "append",
    "аппенд чайлд": "appendChild",
    "ремув": "remove",
    "инсерт": "insert",
    "иннер эйчтиэмэл": "innerHTML",
    "аутер эйчтиэмэл": "outerHTML",
    "текст контент": "textContent",
    "сет атрибут": "setAttribute",
    "гет атрибут": "getAttribute",
    "класслист": "classList",
    "класс лист": "classList",
    "стайл": "style",
    "стайлы": "styles",
    "эвент листенер": "event listener",
    "эдд эвент листенер": "addEventListener",
    "сабмит": "submit",
    "чейндж": "change",
    "инпут": "input",
    "блюр": "blur",
    "скролл": "scroll",
    "ресайз": "resize",
    "лоад": "load",
    "анлоад": "unload",
    "анмаунт": "unmount",
    "рендер": "render",
    "рендеринг": "rendering",
    "ререндер": "rerender",
    "гидрейшн": "hydration",
    "консоль лог": "console.log",
    "логгинг": "logging",
    "дебаг": "debug",
    "дебаггер": "debugger",
    "дебаггинг": "debugging",
    "брейкпоинт": "breakpoint",
    "брейк поинт": "breakpoint",
    "точка останова": "breakpoint",
    "стектрейс": "stacktrace",
    "стэк трейс": "stack trace",
    "эрроры": "errors",
    "ворнинг": "warning",
    "ворнинги": "warnings",
    "варнинг": "warning",
    "инфо": "info",
    "трейс": "trace",
    "ассершн": "assertion",
    "фолдер": "folder",
    "паф": "path",
    "руут": "root",
    "базнейм": "basename",
    "дирнейм": "dirname",
    "экстеншен": "extension",
    "ридфайл": "readFile",
    "райтфайл": "writeFile",
    "эппендфайл": "appendFile",
    "анлинк": "unlink",
    "мкдир": "mkdir",
    "рмдир": "rmdir",
    "ридир": "readdir",
    "стат": "stat",
    "эксистс": "exists",
    "рид": "read",
    "секьюрити": "security",
    "аусентикейшн": "authentication",
    "осоризейшн": "authorization",
    "сайн ин": "sign in",
    "сайн ап": "sign up",
    "сайн аут": "sign out",
    "пассворд": "password",
    "хэшировать": "hash",
    "солт": "salt",
    "энкрипт": "encrypt",
    "дикрипт": "decrypt",
    "серт": "cert",
    "приватный ключ": "private key",
    "публичный ключ": "public key",
    "сикрет": "secret",
    "креденшалс": "credentials",
    "кредс": "creds",
    "ксс": "XSS",
    "иксэсэс": "XSS",
    "ксрф": "CSRF",
    "инджекшн": "injection",
    "эскейп": "escape",
    "санитайз": "sanitize",
    "валидейт": "validate",
    "оптимайз": "optimize",
    "кеш": "cache",
    "кэширование": "caching",
    "мемоизация": "memoization",
    "мемоайз": "memoize",
    "лейзи": "lazy",
    "лэйзи": "lazy",
    "лейзи лоадинг": "lazy loading",
    "код сплиттинг": "code splitting",
    "трии шейкинг": "tree shaking",
    "бандл": "bundle",
    "бандлинг": "bundling",
    "минификация": "minification",
    "минифай": "minify",
    "компрессия": "compression",
    "гзип": "gzip",
    "профайлинг": "profiling",
    "профайлер": "profiler",
    "бенчмарк": "benchmark",
    "латенси": "latency",
    "сруупут": "throughput",
    "пропускная способность": "throughput",
    "вокс": "vox",
    "войс": "voice",
    "шелл": "shell",
    "баш": "bash",
    "зш": "zsh",
    "павершелл": "PowerShell",
    "пауэршелл": "PowerShell",
    "cmd": "cmd",
    "коммандлайн": "command line",
    "сиэлай": "CLI",
    "сли": "CLI",
    "юай": "UI",
    "ю ай": "UI",
    "юэкс": "UX",
    "юзер интерфейс": "user interface",
    "гуи": "GUI",
    "гюи": "GUI",
    "ай ди и": "IDE",
    "вскод": "VS Code",
    "ви эс код": "VS Code",
    "вижуал студио": "Visual Studio",
    "интеллиджей": "IntelliJ",
    "вебшторм": "WebStorm",
    "пайчарм": "PyCharm",
    "саблайм": "Sublime",
    "вим": "Vim",
    "неовим": "Neovim",
    "имакс": "Emacs",
    "нано": "nano",
    "линтер": "linter",
    "линт": "lint",
    "линтинг": "linting",
    "еслинт": "ESLint",
    "преттиер": "Prettier",
    "форматтер": "formatter",
    "сниппет": "snippet",
    "сниппеты": "snippets",
    "автокомплит": "autocomplete",
    "интеллисенс": "IntelliSense",
    "рефактор": "refactor",
    "паст": "paste",
    "пэйст": "paste",
    "пейст": "paste",
    "копи": "copy",
    "андо": "undo",
    "анду": "undo",
    "редо": "redo",
    "риду": "redo",
    "сейв": "save",
    "сэйв": "save",
    "лоуд": "load",
    "опен": "open",
    "оупен": "open",
    "клоуз": "close",
    "клоз": "close",
    "ньюс": "news",
    "криейт": "create",
    "мув": "move",
    "раннинг": "running",
    "рестарт": "restart",
    "клир": "clear",
    "клиа": "clear",
    "гет": "get",
    "пут": "put",
    "патч": "patch",
    "сенд": "send",
    "ресив": "receive",
    "апдейт": "update",
    "апгрейд": "upgrade",
    "даунгрейд": "downgrade",
    "инсталл": "install",
    "анинсталл": "uninstall",
    "энейбл": "enable",
    "дизейбл": "disable",
    "инактив": "inactive",
    "экспанд": "expand",
    "хидден": "hidden",
    "визибл": "visible",
    "олд": "old",
    "бэд": "bad",
    "гуд": "good",
    "биг": "big",
    "смолл": "small",
    "слоу": "slow",
    "хард": "hard",
    "лонг": "long",
    "лоу": "low",
    "фулл": "full",
    "эмпти": "empty",
    "файнал": "final",
    "ферст": "first",
    "ласт": "last",
    "прев": "prev",
    "превиус": "previous",
    "каррент": "current",
    "кастом": "custom",
    "симпл": "simple",
    "бэйсик": "basic",
    "эдванс": "advanced",
    "эдвансд": "advanced",
    "юзер": "user",
    "юзеры": "users",
    "админ": "admin",
    "гест": "guest",
    "хоум": "home",
    "пейдж": "page",
    "пэйдж": "page",
    "линки": "links",
    "урл": "URL",
    "ю ар эл": "URL",
    "месседж": "message",
    "мессадж": "message",
    "мессейдж": "message",
    "комментс": "comments",
    "лайк": "like",
    "шер": "share",
    "шэр": "share",
    "вьюс": "views",
    "дэшборд": "dashboard",
    "дашборд": "dashboard",
    "виджет": "widget",
    "модал": "modal",
    "попап": "popup",
    "поп ап": "popup",
    "тултип": "tooltip",
    "тул тип": "tooltip",
    "дропдаун": "dropdown",
    "дроп даун": "dropdown",
    "сайдбар": "sidebar",
    "сайд бар": "sidebar",
    "футер": "footer",
    "враппер": "wrapper",
    "врэппер": "wrapper",
    "айтем": "item",
    "айтемс": "items",
    "тейбл": "table",
    "роу": "row",
    "колум": "column",
    "колумн": "column",
    "селл": "cell",
    "филд": "field",
    "филды": "fields",
    "лэйбл": "label",
    "плейсхолдер": "placeholder",
    "баттон": "button",
    "батн": "button",
    "чекбокс": "checkbox",
    "селект": "select",
    "оптион": "option",
    "опшн": "option",
    "вэлью": "value",
    "велью": "value",
    "валуе": "value",
    "кей": "key",
    "айди": "id",
    "ай ди": "id",
    "нейм": "name",
    "тайтл": "title",
    "дескрипшн": "description",
    "дескрипшен": "description",
    "пикча": "picture",
    "айкон": "icon",
    "бэкграунд": "background",
    "бордер": "border",
    "марджин": "margin",
    "маргин": "margin",
    "паддинг": "padding",
    "пэддинг": "padding",
    "сайз": "size",
    "сизе": "size",
    "видс": "width",
    "вайдс": "width",
    "хайт": "height",
    "хэйт": "height",
    "колор": "color",
    "дэйт": "date",
    "дейт": "date",
    "таймстэмп": "timestamp",
    "таймаут": "timeout",
    "тайм аут": "timeout",
    "делэй": "delay",
    "дилэй": "delay",
    "саксес": "success",
    "саксесс": "success",
    "фейл": "fail",
    "фэйл": "fail",
    "фейлд": "failed",
    "пендинг": "pending",
    "комплит": "complete",
    "комплитед": "completed",
    "реди": "ready",
    "рэди": "ready",
    "лоадинг": "loading",
    "лоудинг": "loading",
    "процессинг": "processing",
    "вэйтинг": "waiting",
    "вейтинг": "waiting",
    "хелп": "help",
    "хэлп": "help",
    "йес": "yes",
    "кэнсел": "cancel",
    "кансел": "cancel",
    "рижект": "reject",
    "эпрув": "approve",
    "эппрув": "approve",
    "дикляйн": "decline",
    "деклайн": "decline",
    "конфёрм": "confirm",
    "конферм": "confirm",
    "ченж": "change",
    "эдит": "edit",
    "модифай": "modify",
    "трансформ": "transform",
    "парс": "parse",
    "парсить": "parse",
    "верифай": "verify",
    "фикс": "fix",
    "солв": "solve",
    "ризолв": "resolve",
    "хендл": "handle",
    "хэндл": "handle",
    "аналайз": "analyze",
    "сёрч": "search",
    "препенд": "prepend",
    "инсёрт": "insert",
    "дупликейт": "duplicate",
    "ехе": ".exe",
    "ексе": ".exe",
    "экзе": ".exe",
    "джейэс": ".js",
    "джиэс": ".js",
    "тиэс": ".ts",
    "эмди": ".md",
    "маркдаун": ".md",
    "ямлфайл": ".yaml",
    "тхт": ".txt",
    "зип": ".zip",
    "гз": ".gz",
    "таргз": ".tar.gz",
    "рар": ".rar",
    "севен зип": ".7z",
    "пнг": ".png",
    "джипег": ".jpg",
    "джпг": ".jpg",
    "джипиджи": ".jpg",
    "гиф": ".gif",
    "свг": ".svg",
    "вебп": ".webp",
    "айко": ".ico",
    "пдф": ".pdf",
    "докс": ".docx",
    "иксэль": ".xlsx",
    "эксель": ".xlsx",
    "цсв": ".csv",
    "сиэсви": ".csv",
    "эсКюЭль": ".sql",
    "скьюлайт": "SQLite",
    "скиллайт": "SQLite",
    "ск лайт": "SQLite",
    "эскюлайт": "SQLite",
    "дотенв": ".env",
    "енв": ".env",
    "мейкфайл": "Makefile",
    "рэг": "RAG",
    "файнтюн": "fine-tune",
    "файн тюн": "fine-tune",
    "промптинг": "prompting",
    "промпт инжиниринг": "prompt engineering",
    "токенайзер": "tokenizer",
    "токенизация": "tokenization",
    "оверфиттинг": "overfitting",
    "андерфиттинг": "underfitting",
    "хайперпараметр": "hyperparameter",
    "хайперпараметры": "hyperparameters",
    "датасет": "dataset",
    "датасеты": "datasets",
    "лосс": "loss",
    "батч": "batch",
    "батчи": "batches",
    "аутпут": "output",
    "лейер": "layer",
    "чекпоинт": "checkpoint",
    "зирошот": "zero-shot",
    "зеро шот": "zero-shot",
    "фьюшот": "few-shot",
    "фью шот": "few-shot",
    "ризонинг": "reasoning",
    "халлюцинация": "hallucination",
    "квантизация": "quantization",
    "семплинг": "sampling",
    "сэмплинг": "sampling",
    "логиты": "logits",
    "софтмакс": "softmax",
    "инстракт": "instruct",
    "бэкпроп": "backprop",
    "эттеншн": "attention",
    "аттеншн": "attention",
}
